<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild> 
    <PackageId>Cabal.Scheduler</PackageId>
    <Version>1.0.0-beta</Version>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web\UI\dashboard.html" />
  </ItemGroup>



  <ItemGroup>
    <InternalsVisibleTo Include="Cabal.Tests" />
    <InternalsVisibleTo Include="Cabal.Benchmarks" />
  </ItemGroup>
</Project>